DROP TABLE IF EXISTS {{LOGIN}}_LOGEVENT_PHOENIX;
CREATE TABLE {{LOGIN}}_LOGEVENT_PHOENIX(
TIMESTAMP VARCHAR NOT NULL,
USER_ID INTEGER NOT NULL,
SONG_ID INTEGER NOT NULL,
SERVER VARCHAR,
EVENT VARCHAR,
SONG_DURATION INTEGER,
CONSTRAINT PK PRIMARY KEY  (TIMESTAMP,USER_ID,SONG_ID)
);
